/** Declaration file generated by dts-gen */

export = read_metadata;

declare function read_metadata(path: any, done: any): any;

declare namespace read_metadata {
    const prototype: {
    };

    function sync(path: any): any;

    namespace sync {
        const prototype: {
        };

    }

}

