/** Declaration file generated by dts-gen */

export = validate_npm_package_name;

declare function validate_npm_package_name(name: any): any;

declare namespace validate_npm_package_name {
    const prototype: {
    };

    const scopedPackagePattern: RegExp;

}

